service: graphql-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: dev
  environment:
    NODE_ENV: production
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:Invoke"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:
  graphqlFunction:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
